"""Review forms and stable task actions; remaining selection belongs to its task."""
from PySide6.QtCore import Qt
from PySide6.QtGui import QTextOption
from PySide6.QtWidgets import (QWidget, QVBoxLayout, QHBoxLayout, QFormLayout, QLabel,
    QLineEdit, QPushButton, QComboBox, QTabWidget, QListWidget, QPlainTextEdit, QTextEdit,
    QSplitter, QCheckBox, QToolButton, QScrollArea, QGridLayout, QFrame, QTableWidget, QHeaderView, QMenu, QSizePolicy, QLayout)
from .ui_common import AlignedComboBox
from .review_ui import (page_layout, scroll_page, section_line, guard_values,
    address_field, match_tabs, ComicTable, ResultPageDrop, ScopeComboBox)
from .ai_config import PROVIDERS, THINKING_MODES, EFFORTS, RUNTIME_DEFAULTS
from .ai_txt_page import TxtPage
from .ui_common import FixedMaskKey, DetailHeightGrip, DetailSplitter


def build(dialog):
    d = dialog
    d.setObjectName('reviewDialog')
    root = QVBoxLayout(d)
    root.setContentsMargins(9,4,9,9)
    d.supplement_strip = QFrame()
    d.supplement_strip.setObjectName('supplementStrip')
    d.supplement_strip.setStyleSheet('QFrame#supplementStrip { background: white; border: 1px solid #d6e3ef; border-left: 3px solid #acc2d7; border-radius: 3px; }')
    shared = QHBoxLayout(d.supplement_strip); shared.setContentsMargins(8,5,8,5)
    d.supplement_label = QLabel()
    d.supplement_label.setWordWrap(True)
    shared.addWidget(d.supplement_label,1)
    button = QPushButton('补充依据')
    button.clicked.connect(d._edit_supplements)
    shared.addWidget(button,0,Qt.AlignVCenter)
    root.addWidget(d.supplement_strip)
    d.tabs = QTabWidget()
    match_tabs(d.tabs)
    root.addWidget(d.tabs,1)
    api = QWidget(); api.setObjectName('reviewApiPage')
    api_scroll = scroll_page(api); api_scroll.setObjectName('reviewApiScroll')
    api.setStyleSheet('QWidget#reviewApiPage, QWidget#reviewApiEditor { background-color: white; }')
    api_scroll.setStyleSheet('QScrollArea#reviewApiScroll { background-color: white; }')
    api_scroll.viewport().setStyleSheet('background-color: white;')
    d.api_scroll = api_scroll
    form = page_layout(api)
    d.scope_title = QLabel('选择范围')
    form.addWidget(d.scope_title)
    scope_row = QHBoxLayout()
    d.scope_label = QLabel('', api); d.scope_label.hide()
    d.scope = ScopeComboBox()
    for label, value in [('已勾选漫画','checked'),('指定分类','categories'),('全部漫画','all'),('当前搜索结果','search')]:
        d.scope.addItem(label,value)
    d.scope.currentIndexChanged.connect(d._update_scope_count)
    d.scope.activated.connect(lambda *_: d._update_scope_count())
    scope_row.addWidget(d.scope,1)
    d.choose_category_btn = QPushButton('选择分类')
    d.choose_category_btn.clicked.connect(d._choose_categories)
    scope_row.addWidget(d.choose_category_btn)
    form.addLayout(scope_row)
    d.count_label = QLabel(); d.count_label.setWordWrap(True); form.addWidget(d.count_label)
    d.saved_config_label = QLabel(); d.saved_config_label.setWordWrap(True); form.addWidget(d.saved_config_label)
    d.saved_model_label = QLabel(); d.saved_model_label.setWordWrap(True); form.addWidget(d.saved_model_label)
    d.start_btn = QPushButton('开始 API 复核（使用已保存配置）')
    d.start_btn.clicked.connect(d._start); form.addWidget(d.start_btn)
    config_row = QHBoxLayout()
    d.profiles = AlignedComboBox(); d.profiles.currentIndexChanged.connect(d._select_profile)
    d.profiles_label = QLabel('当前配置'); config_row.addWidget(d.profiles_label); config_row.addWidget(d.profiles,1)
    d.edit_btn = QPushButton('编辑配置'); d.edit_btn.clicked.connect(d._unlock_editor); config_row.addWidget(d.edit_btn)
    d.cancel_btn = QPushButton('取消编辑'); d.cancel_btn.clicked.connect(d._cancel_config)
    config_row.addWidget(d.cancel_btn); form.addLayout(config_row)
    d.config_editor = QWidget(); d.config_editor.setObjectName('reviewApiEditor'); settings = QVBoxLayout(d.config_editor); settings.setContentsMargins(0,0,0,0); settings.setSpacing(6)
    buttons = QHBoxLayout()
    d.new_profile_btn = QPushButton('新增'); d.copy_profile_btn = QPushButton('复制')
    d.delete_profile_btn = QPushButton('删除')
    for w, action in [(d.new_profile_btn,d._new_profile),(d.copy_profile_btn,d._copy_profile),(d.delete_profile_btn,d._delete_profile)]:
        w.clicked.connect(action); buttons.addWidget(w)
    settings.addLayout(buttons)
    label_width = max(d.fontMetrics().horizontalAdvance(label) for label in ['配置名称','Endpoint','API Key','每请求本数','接口类型','思考模式','失败重试']) + 4
    d._config_form_labels = []
    d._config_form_fields = []
    def row(form, label, widget):
        form.setLabelAlignment(Qt.AlignLeft|Qt.AlignVCenter)
        text = QLabel(label); text.setAlignment(Qt.AlignLeft|Qt.AlignVCenter); text.setMinimumWidth(label_width); d._config_form_labels.append(text); d._config_form_fields.append((text,widget)); form.addRow(text,widget)
    fields = QFormLayout(); fields.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow); fields.setVerticalSpacing(6)
    d.profile_name = QLineEdit(); d.profile_name.setMaxLength(80)
    d.endpoint = QLineEdit(); d.endpoint.setPlaceholderText('供应商提供的兼容接口地址')
    d.key = FixedMaskKey()
    d.model = QLineEdit(); d.model.setPlaceholderText('例如 qwen3.7-flash')
    d.provider = AlignedComboBox()
    for value,label in PROVIDERS.items(): d.provider.addItem(label,value)
    d.quick_fill = AlignedComboBox()
    for label,value in [('快速填写接口',''),('DeepSeek 官方','deepseek'),('阿里百炼（国内）','qwen'),('阿里百炼（国际）','qwen_intl'),('OpenAI 兼容接口','openai'),('硅基流动','siliconflow'),('OpenRouter','openrouter')]: d.quick_fill.addItem(label,value)
    d.quick_fill.activated.connect(d._quick_fill)
    row(fields,'快速填写',d.quick_fill)
    for label,w in [('配置名称',d.profile_name),('Endpoint',d.endpoint),('API Key',d.key),('模型',d.model)]: row(fields,label,w)
    settings.addLayout(fields)
    settings.addWidget(section_line())
    d.advanced_toggle = QToolButton(); d.advanced_toggle.setText('高级参数'); d.advanced_toggle.setCheckable(True)
    d.advanced_toggle.setToolButtonStyle(Qt.ToolButtonTextBesideIcon); d.advanced_toggle.setArrowType(Qt.RightArrow)
    d.advanced_toggle.setProperty('reviewFoldHeader', True)
    settings.addWidget(d.advanced_toggle)
    d.advanced = QWidget(); advanced = QFormLayout(d.advanced); advanced.setContentsMargins(0,0,0,0)
    advanced.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow); advanced.setVerticalSpacing(6)
    d.advanced_toggle.toggled.connect(d.advanced.setVisible)
    d.advanced_toggle.toggled.connect(lambda opened:d.advanced_toggle.setArrowType(Qt.DownArrow if opened else Qt.RightArrow))
    d.provider.setToolTip('仅官方DeepSeek＋DeepSeek、百炼＋Qwen使用内置自动参数；其他组合使用自定义请求参数。')
    row(advanced,'接口类型',d.provider)
    d.thinking = AlignedComboBox()
    for value,label in THINKING_MODES.items(): d.thinking.addItem(label,value)
    d.effort = AlignedComboBox()
    for value,label in EFFORTS.items(): d.effort.addItem(label,value)
    row(advanced,'思考模式',d.thinking); row(advanced,'思考强度',d.effort)
    d.max_tokens = AlignedComboBox(); d.max_tokens.setEditable(True)
    for value in (8192,16384,32768,65536): d.max_tokens.addItem(f'{value//1024}k/{value}',value)
    row(advanced,'最大Token',d.max_tokens)
    d.custom_toggle = QLabel('自定义请求参数')
    d.custom_parameters = QPlainTextEdit(); d.custom_parameters.setPlaceholderText('{"temperature": 0.2}')
    d.custom_parameters.setFixedHeight(d.fontMetrics().lineSpacing()*5+12)
    advanced.addRow(d.custom_toggle); advanced.addRow(d.custom_parameters)
    d.runtime_edits = {}
    for key,label in [('batch_size','每请求本数'),('concurrency','并发数'),('timeout_seconds','超时秒数'),('max_retries','失败重试')]:
        w = QLineEdit(str(RUNTIME_DEFAULTS[key]))
        w.setPlaceholderText('非负整数' if key=='max_retries' else '正整数')
        d.runtime_edits[key] = w; row(advanced,label,w)
    d.restore_btn = QPushButton('恢复推荐运行参数'); d.restore_btn.clicked.connect(d._restore_runtime)
    advanced.addRow(d.restore_btn)
    settings.addWidget(d.advanced); d.advanced.hide()
    settings.addWidget(section_line())
    d.price_toggle = QToolButton(); d.price_toggle.setText('费用估算'); d.price_toggle.setCheckable(True)
    d.price_toggle.setToolButtonStyle(Qt.ToolButtonTextBesideIcon); d.price_toggle.setArrowType(Qt.RightArrow)
    d.price_toggle.setProperty('reviewFoldHeader', True)
    d.price_toggle.toggled.connect(lambda opened:d.price_toggle.setArrowType(Qt.DownArrow if opened else Qt.RightArrow))
    settings.addWidget(d.price_toggle)
    d.price_summary = QLabel(); d.price_summary.setWordWrap(True)
    d.price_summary.hide()
    d.price_panel = QWidget(); pf = QFormLayout(d.price_panel); d.price_toggle.toggled.connect(d.price_panel.setVisible); pf.setContentsMargins(0,0,0,0); pf.setVerticalSpacing(6); pf.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
    d.price_kind = AlignedComboBox()
    preset_row = QWidget(); preset_layout = QHBoxLayout(preset_row); preset_layout.setContentsMargins(0,0,0,0)
    d.price_kind.setMinimumWidth(0); d.price_kind.setSizePolicy(QSizePolicy.Ignored,QSizePolicy.Fixed)
    preset_layout.addWidget(d.price_kind,1)
    d.new_price_btn = QPushButton('新增预设'); d.new_price_btn.clicked.connect(d._new_price_preset)
    d.delete_price_btn = QPushButton('删除预设'); d.delete_price_btn.clicked.connect(d._delete_price_preset)
    for button in (d.new_price_btn,d.delete_price_btn): preset_layout.addWidget(button)
    row(pf,'费用估算预设',preset_row)
    d.price_name = QLineEdit(); d.price_name.setMaxLength(80); row(pf,'预设名称',d.price_name)
    d.price_tier = AlignedComboBox(); d.price_tier.currentIndexChanged.connect(d._change_price_tier); row(pf,'价格档位',d.price_tier)
    d.price_status = QLabel(); d.price_status.hide()
    d.currency = AlignedComboBox(); d.currency.addItem('人民币/百万Token','CNY'); d.currency.addItem('美元/百万Token','USD'); row(pf,'币种',d.currency)
    d.price_edits = {}
    for key,label in [('input','输入未命中'),('cached','输入命中'),('output','输出')]:
        w = QLineEdit(); w.setPlaceholderText('每百万Token单价'); d.price_edits[key] = w; row(pf,label,w)
        w.textChanged.connect(d._update_price_summary)
    d.currency.currentIndexChanged.connect(d._update_price_summary)
    d.price_hint = QLabel(); d.price_hint.hide()
    d.price_kind.currentIndexChanged.connect(d._change_price_kind)
    settings.addWidget(d.price_panel); d.price_panel.hide()
    controls = QHBoxLayout()
    d.save_btn = QPushButton('保存并使用'); d.save_btn.clicked.connect(d._save_config)
    d.test_btn = QPushButton('测试当前配置'); d.test_btn.clicked.connect(d._test_config)
    for w in [d.save_btn,d.test_btn]: controls.addWidget(w)
    settings.addLayout(controls)
    d.config_note = QLabel(); d.config_note.setWordWrap(True)
    form.addWidget(d.config_editor); form.addWidget(d.config_note); form.addStretch()
    for w in [d.provider,d.thinking,d.effort]: w.currentIndexChanged.connect(d._update_provider_hint)
    for w in [d.endpoint,d.model]: w.textChanged.connect(d._update_provider_hint)
    d.tabs.addTab(api_scroll,'API复核')
    d.txt_page = TxtPage(d.owner); d.tabs.addTab(scroll_page(d.txt_page),'TXT复核')
    task_page = QWidget(); tl = page_layout(task_page)
    d.task_scroll = scroll_page(task_page)
    tl.setSizeConstraint(QLayout.SetMinimumSize)
    # Match the scroll gutter of the two form pages.
    tl.setContentsMargins(8,8,8,8)
    filters = QHBoxLayout()
    d.task_search = QLineEdit(); d.task_search.setPlaceholderText('查找日期、任务编号、模型或漫画名')
    d.task_type = AlignedComboBox()
    for label,value in [('所有类型',''),('API','API'),('TXT','TXT')]: d.task_type.addItem(label,value)
    d.task_state_filter = AlignedComboBox()
    for label,value in [('所有状态',''),('运行中','running'),('待处理','pending'),('有失败','failed'),('已完成','completed')]: d.task_state_filter.addItem(label,value)
    for w in [d.task_search,d.task_type,d.task_state_filter]: filters.addWidget(w,1)
    tl.addLayout(filters)
    d.task_search.textChanged.connect(d._filter_refresh)
    d.task_type.currentIndexChanged.connect(d._filter_refresh); d.task_state_filter.currentIndexChanged.connect(d._filter_refresh)
    d.task_list = QListWidget(); d.task_list.currentRowChanged.connect(d._show_task)
    d.task_detail = QPlainTextEdit(); d.task_detail.setReadOnly(True)
    d.process_detail = QPlainTextEdit(); d.process_detail.setReadOnly(True)
    for text in (d.task_detail,d.process_detail): text.setFrameShape(QFrame.NoFrame)
    d.comic_detail = ComicTable()
    d.comic_detail.setHorizontalHeaderLabels(['','漫画','状态','判断','建议名','原因 / 应用'])
    d.comic_detail.enable_select_all_header(lambda item:
        getattr(d, '_comic_status', {}).get(item.data(Qt.UserRole)) == 'ready')
    d.comic_detail.setWordWrap(False); d.comic_detail.setEditTriggers(QTableWidget.NoEditTriggers)
    d.comic_detail.setSelectionBehavior(QTableWidget.SelectRows); d.comic_detail.verticalHeader().hide()
    header = d.comic_detail.horizontalHeader()
    d.comic_detail.horizontalHeaderItem(0).setToolTip('点击全选 / 清空可复核剩余项；资料变化项可单独勾选后右键新建复核。')
    header.sectionClicked.connect(d._comic_header_clicked)
    d.comic_detail.itemChanged.connect(d._remaining_scope_changed)
    d.comic_detail.setContextMenuPolicy(Qt.CustomContextMenu); d.comic_detail.customContextMenuRequested.connect(d._comic_menu)
    d.detail_tabs = QTabWidget()
    match_tabs(d.detail_tabs)
    d.detail_tabs.addTab(d.task_detail,'任务概览')
    process_page = QWidget(); process_layout = QVBoxLayout(process_page); process_layout.setContentsMargins(0,0,0,0)
    process_layout.addWidget(d.process_detail,1)
    d.txt_retry_btn = QPushButton('重新导出'); d.txt_retry_btn.clicked.connect(lambda:d._txt_action('retry'))
    process_layout.addWidget(d.txt_retry_btn); d.txt_retry_btn.hide()
    d.detail_tabs.addTab(process_page,'处理记录')
    d.detail_tabs.addTab(d.comic_detail,'漫画明细')
    d.txt_page.mode.currentIndexChanged.connect(d._remaining_scope_changed); d.txt_page.value.valueChanged.connect(d._remaining_scope_changed)
    d.task_splitter = DetailSplitter(Qt.Vertical); d.task_splitter.setChildrenCollapsible(False)
    d.task_splitter.setHandleWidth(5)
    d.task_splitter.addWidget(d.task_list); d.task_splitter.addWidget(d.detail_tabs)
    d.task_list.setMinimumHeight(65); d.detail_tabs.setMinimumHeight(120)
    d.task_splitter.setSizes([140,240]); tl.addWidget(d.task_splitter,1)
    d.detail_height_grip = DetailHeightGrip(d.task_splitter)
    tl.addWidget(d.detail_height_grip)
    tl.setSpacing(6)
    # The grip is also the only separator below the detail pane.
    tl.setStretch(tl.indexOf(d.detail_height_grip),0)
    d.remaining_scope_label = QLabel(); d.remaining_scope_label.setMinimumWidth(0); d.remaining_scope_label.setFixedHeight(d.fontMetrics().height()+6)
    tl.addWidget(d.remaining_scope_label)
    actions = QHBoxLayout()
    d.stop_btn = QPushButton('停止派发新组'); d.stop_btn.clicked.connect(d.owner.stop_api_task)
    d.remaining_btn = QPushButton('API复核剩余项'); d.remaining_btn.clicked.connect(d._resume)
    d.api_txt_btn = QPushButton('TXT复核剩余项'); d.api_txt_btn.clicked.connect(d._api_to_txt)
    for w in [d.stop_btn,d.remaining_btn,d.api_txt_btn]: actions.addWidget(w,1)
    tl.addLayout(actions)
    import_row = QHBoxLayout()
    d.import_results_btn = QPushButton('导入TXT结果'); d.import_results_btn.clicked.connect(d.txt_page.choose_results)
    d.txt_folder_btn = QPushButton('打开导出文件夹'); d.txt_folder_btn.clicked.connect(lambda:d._txt_action('folder'))
    for w in [d.import_results_btn,d.txt_folder_btn]: import_row.addWidget(w,1)
    tl.addLayout(import_row)
    directory_row = QHBoxLayout()
    directory_row.addWidget(QLabel('结果目录'))
    d.directory_label = address_field(); directory_row.addWidget(d.directory_label,1)
    d.directory_change_btn = QPushButton('更改目录'); d.directory_change_btn.clicked.connect(d.txt_page.choose_directory); directory_row.addWidget(d.directory_change_btn)
    d.directory_import_btn = QPushButton('从结果目录导入'); d.directory_import_btn.clicked.connect(d._import_selected_directory)
    directory_row.addWidget(d.directory_import_btn)
    tl.addLayout(directory_row)
    from .ai_archive_ui import ArchiveControls
    d.archive_controls = ArchiveControls(d.owner); tl.addWidget(d.archive_controls)
    d.directory_target_label = QLabel(); d.directory_target_label.setMinimumWidth(0); d.directory_target_label.setFixedHeight(d.fontMetrics().height()+4); tl.addWidget(d.directory_target_label)
    feedback_row = QHBoxLayout()
    d.directory_feedback = QLabel(); d.directory_feedback.setMinimumWidth(0)
    d.directory_feedback.setAlignment(Qt.AlignLeft|Qt.AlignVCenter)
    d.directory_feedback.setSizePolicy(QSizePolicy.Ignored,QSizePolicy.Preferred)
    d.directory_feedback.setTextInteractionFlags(Qt.TextSelectableByMouse)
    feedback_row.addWidget(d.directory_feedback,1)
    d.import_details_btn = QPushButton('查看导入异常'); d.import_details_btn.clicked.connect(d._show_import_details); feedback_row.addWidget(d.import_details_btn,0,Qt.AlignVCenter)
    tl.addLayout(feedback_row)
    d.directory_extra_feedback = QLabel(); d.directory_extra_feedback.setWordWrap(True)
    d.directory_extra_feedback.setMinimumWidth(0); d.directory_extra_feedback.hide()
    tl.addWidget(d.directory_extra_feedback)
    d.import_anomalies = QPlainTextEdit(); d.import_anomalies.setReadOnly(True)
    d.import_anomalies.setFixedHeight(110); d.import_anomalies.hide()
    tl.addWidget(d.import_anomalies)
    d.logs_panel = QWidget(); logs = QHBoxLayout(d.logs_panel); logs.setContentsMargins(0,0,0,0)
    d.logs_btn = QPushButton('日志文件夹'); d.logs_btn.clicked.connect(d._open_logs)
    d.log_view_btn = QPushButton('查找日志 / 失败定位'); d.log_view_btn.clicked.connect(d._view_logs)
    d.copy_diag_btn = QPushButton('复制脱敏诊断'); d.copy_diag_btn.clicked.connect(d._copy_diagnostics)
    for w in [d.logs_btn,d.log_view_btn,d.copy_diag_btn]: logs.addWidget(w,1)
    tl.addWidget(d.logs_panel)
    d.tabs.addTab(d.task_scroll,'任务与日志')
    d._editor_unlocked = False
    d._price_snapshot = {}
    for label in (d.directory_target_label, d.remaining_scope_label):
        label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Fixed)
    for label in api.findChildren(QLabel):
        label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Fixed)
    for label in [*d._config_form_labels,d.scope_label,d.profiles_label]:
        label.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
    d._txt_drop_receiver = ResultPageDrop(d.tabs.widget(1), d.owner)
    d._task_drop_receiver = ResultPageDrop(task_page, d.owner)
    d._init_comic_column_widths()
    d._align_form_labels()
    guard_values(d)
    d._sync_review_fonts()
